### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/circuitjs1#1]
A ToDo list of things to do here:

- [ ] Add more screenshots
- [ ] Re-organize the README
- [x] Add Bash scripts and Gradle/Maven config files
- [ ] Add all issue Labels
- [ ] Update circuitjs `VersionString` and `About` text
- [x] **TEST** all scripts and builds on Vanilla clone
- [ ] Add github site for application deployment
